/** Índice emoji → palavras-chave (PT) para busca no picker. */
export const EMOJI_SEARCH_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  // Rostos
  "😀": ["feliz", "sorriso", "alegre", "riso", "rosto"],
  "😃": ["feliz", "sorriso", "alegre"],
  "😄": ["feliz", "sorriso", "risada"],
  "😁": ["feliz", "sorriso", "dente"],
  "😆": ["rindo", "risada", "feliz"],
  "😅": ["nervoso", "suor", "riso"],
  "🤣": ["rindo", "rolando", "risada", "morrer"],
  "😂": ["chorando", "riso", "lagrima", "engracado"],
  "🙂": ["sorriso", "leve", "rosto"],
  "😉": ["piscada", "flerte"],
  "😊": ["feliz", "timido", "sorriso"],
  "😇": ["anjo", "inocente"],
  "🥰": ["amor", "apaixonado", "carinho"],
  "😍": ["amor", "apaixonado", "olhos"],
  "🤩": ["estrela", "empolgado", "fã"],
  "😘": ["beijo", "amor"],
  "😋": ["delicia", "comida", "gostoso"],
  "😛": ["lingua", "palhaço"],
  "😜": ["palhaço", "loucura", "piscada"],
  "🤪": ["louco", "doido", "zoeira"],
  "🤑": ["dinheiro", "rico", "grana"],
  "🤗": ["abraco", "carinho"],
  "🤔": ["pensando", "duvida", "hmm"],
  "😐": ["neutro", "serio", "sem"],
  "😑": ["sem", "expressao"],
  "😏": ["sarcasmo", "malicioso", "smirk"],
  "😒": ["chato", "entediado"],
  "🙄": ["revirar", "olho", "chato"],
  "😬": ["constrangido", "awkward"],
  "😌": ["aliviado", "paz"],
  "😔": ["triste", "pensativo"],
  "😪": ["sono", "cansado"],
  "😴": ["dormindo", "sono", "zzz"],
  "😷": ["mascara", "doente", "gripe"],
  "🤒": ["doente", "febre", "termometro"],
  "🤮": ["vomito", "nojo"],
  "🥵": ["calor", "quente"],
  "🥶": ["frio", "gelado"],
  "🤯": ["explodir", "mente", "chocado"],
  "🥳": ["festa", "parabens", "aniversario"],
  "😎": ["legal", "oculos", "sol"],
  "🤓": ["nerd", "estudioso"],
  "😕": ["confuso", "triste"],
  "😟": ["preocupado", "ansioso"],
  "😮": ["surpresa", "boquiaberto"],
  "😯": ["surpresa"],
  "😲": ["chocado", "surpresa"],
  "😳": ["vergonha", "corado"],
  "🥺": ["pidao", "fofo", "por favor"],
  "😢": ["chorando", "triste", "lagrima"],
  "😭": ["chorando", "muito", "triste"],
  "😱": ["grito", "medo", "terror"],
  "😡": ["raiva", "bravo", "furioso"],
  "😠": ["bravo", "irritado"],
  "🤬": ["palavrao", "raiva"],

  // Gestos
  "👋": ["oi", "tchau", "acenar", "mao"],
  "👍": ["joinha", "ok", "positivo", "sim"],
  "👎": ["nao", "negativo", "ruim"],
  "👏": ["palmas", "aplauso", "parabens"],
  "🙌": ["celebrar", "maos", "aleluia"],
  "🙏": ["rezar", "por favor", "obrigado"],
  "💪": ["forca", "musculo", "treino"],
  "👌": ["ok", "perfeito"],
  "✌️": ["paz", "vitoria", "dois"],
  "🤞": ["sorte", "dedos"],
  "🤝": ["acordo", "parceria", "aperto"],
  "👀": ["olhos", "olhando", "ver"],

  // Corações
  "❤️": ["amor", "coracao", "vermelho"],
  "🧡": ["amor", "laranja"],
  "💛": ["amor", "amarelo", "amizade"],
  "💚": ["amor", "verde"],
  "💙": ["amor", "azul"],
  "💜": ["amor", "roxo"],
  "🖤": ["amor", "preto"],
  "💔": ["coracao", "partido", "triste", "termino"],
  "💕": ["amor", "carinho"],
  "💖": ["amor", "brilho"],
  "💘": ["amor", "cupido", "flecha"],
  "💋": ["beijo", "batom"],
  "🌹": ["rosa", "flor", "amor", "romantico"],

  // Diversão / esporte
  "🎮": ["jogo", "videogame", "game", "play"],
  "🕹️": ["jogo", "controle", "arcade"],
  "🎯": ["alvo", "dardo", "precisao"],
  "🎲": ["dado", "sorte", "rpg"],
  "🎵": ["musica", "nota"],
  "🎶": ["musica", "notas"],
  "🎸": ["guitarra", "musica", "rock"],
  "🎤": ["microfone", "cantar", "karaoke"],
  "🎧": ["fone", "musica", "ouvir"],
  "📺": ["tv", "televisao", "serie"],
  "🏆": ["trofeu", "campeao", "vitoria", "win"],
  "🥇": ["ouro", "primeiro", "medalha"],
  "⚽": ["futebol", "bola", "gol"],
  "🏀": ["basquete", "bola"],
  "🎾": ["tenis", "bola"],

  // Comida e bebida
  "☕": ["cafe", "cha", "bebida", "manha", "coffee"],
  "🍵": ["cha", "bebida"],
  "🧋": ["bubble", "tea", "cha", "bebida"],
  "🍺": ["cerveja", "beer", "chopp", "bebida", "bar", "alcool"],
  "🍻": ["cerveja", "brinde", "bebida", "bar"],
  "🍷": ["vinho", "wine", "taca", "bebida", "alcool", "tinto"],
  "🥂": ["champanhe", "brinde", "espumante", "bebida", "celebrar"],
  "🍾": ["champanhe", "festa", "bebida", "brinde"],
  "🥃": ["whisky", "drink", "bebida", "alcool", "copo"],
  "🍹": ["drink", "coquetel", "bebida", "tropical", "caipirinha"],
  "🥤": ["refrigerante", "suco", "bebida", "copo"],
  "🧃": ["suco", "caixinha", "bebida"],
  "🍕": ["pizza", "comida", "italiana"],
  "🍔": ["hamburguer", "burger", "comida", "lanche"],
  "🌮": ["taco", "mexicano", "comida"],
  "🌭": ["cachorro", "quente", "hotdog", "comida"],
  "🍟": ["batata", "frita", "comida"],
  "🍿": ["pipoca", "cinema", "filme", "lanche"],
  "🍩": ["donut", "rosquinha", "doce"],
  "🍰": ["bolo", "doce", "aniversario", "fatia"],
  "🎂": ["bolo", "aniversario", "parabens", "doce"],
  "🍦": ["sorvete", "gelado", "doce"],
  "🍫": ["chocolate", "doce"],
  "🍎": ["maca", "fruta"],
  "🍌": ["banana", "fruta"],
  "🍉": ["melancia", "fruta"],
  "🍇": ["uva", "vinho", "fruta"],
  "🥑": ["abacate", "avo", "comida"],

  // Objetos / símbolos
  "🔥": ["fogo", "quente", "lit", "flame"],
  "💯": ["cem", "perfeito", "nota"],
  "✨": ["brilho", "estrela", "magia", "sparkle"],
  "⭐": ["estrela", "favorito"],
  "🌟": ["estrela", "brilho"],
  "⚡": ["raio", "energia", "rapido"],
  "💥": ["explosao", "boom"],
  "🎉": ["festa", "parabens", "celebrar", "confete"],
  "🎊": ["festa", "confete"],
  "🎈": ["balao", "festa", "aniversario"],
  "🎁": ["presente", "gift", "caixa"],
  "✅": ["check", "sim", "feito", "ok"],
  "❌": ["nao", "erro", "x"],
  "❓": ["pergunta", "duvida"],
  "💬": ["balao", "fala", "chat", "mensagem"],
  "🚀": ["foguete", "espaco", "rapido", "lancar"],
  "👑": ["rei", "rainha", "coroa", "rei"],
  "💎": ["diamante", "rico", "luxo"],
  "🤡": ["palhaço", "circo", "zoeira"],
  "👻": ["fantasma", "halloween"],
  "💀": ["caveira", "morte", "skull"],
  "😈": ["diabo", "mal", "horn"],
  "🌈": ["arco", "iris", "lgbt", "cores"],
  "☀️": ["sol", "dia", "calor"],
  "🌙": ["lua", "noite"],

  // Animais
  "🐶": ["cachorro", "cao", "dog", "pet"],
  "🐱": ["gato", "cat", "pet"],
  "🐭": ["rato", "mouse"],
  "🐹": ["hamster", "pet"],
  "🐰": ["coelho", "pascoa"],
  "🦊": ["raposa", "fox"],
  "🐻": ["urso", "bear"],
  "🐼": ["panda"],
  "🐯": ["tigre"],
  "🦁": ["leao", "lion"],
  "🐮": ["vaca", "mu"],
  "🐷": ["porco", "pig"],
  "🐸": ["sapo", "frog"],
  "🐵": ["macaco", "mono"],
  "🐔": ["galinha", "frango"],
  "🐧": ["pinguim"],
  "🦄": ["unicornio", "magia"],
  "🐝": ["abelha", "bee"],
  "🦋": ["borboleta"],
  "🐢": ["tartaruga"],
  "🐍": ["cobra", "snake"],
  "🐙": ["polvo"],
  "🦈": ["tubarao"],
  "🐠": ["peixe", "aquario"],
};
