export const usersInQueue = [
    {
        id: '1',
        nick: 'JohnDoe',
        tag: '#BR1',
        role: 'Support',
        rank: 'Platinum IV',
        search_role: 'Top',
        search_rank: 'Platinum III',
    },
    {
        id: '2',
        nick: 'ShadowWolf',
        tag: '#NA23',
        role: 'Top',
        rank: 'Gold II',
        search_role: 'Mid',
        search_rank: 'Gold I',
    },
    {
        id: '3',
        nick: 'MightyFox',
        tag: '#EUW88',
        role: 'Jungle',
        rank: 'Silver III',
        search_role: 'ADC',
        search_rank: 'Silver I',
    },
    {
        id: '4',
        nick: 'LunaKnight',
        tag: '#BR99',
        role: 'Mid',
        rank: 'Diamond IV',
        search_role: 'Top',
        search_rank: 'Diamond III',
    },
    {
        id: '5',
        nick: 'SilentArrow',
        tag: '#LAN12',
        role: 'ADC',
        rank: 'Bronze I',
        search_role: 'Support',
        search_rank: 'Silver IV',
    },
    {
        id: '6',
        nick: 'CrimsonBlade',
        tag: '#KR77',
        role: 'Support',
        rank: 'Emerald II',
        search_role: 'Jungle',
        search_rank: 'Emerald I',
    },
    {
        id: '7',
        nick: 'WindReaper',
        tag: '#NA43',
        role: 'Top',
        rank: 'Iron I',
        search_role: 'Top',
        search_rank: 'Bronze IV',
    },
    {
        id: '8',
        nick: 'BlueStorm',
        tag: '#EUW7',
        role: 'Mid',
        rank: 'Gold IV',
        search_role: 'Jungle',
        search_rank: 'Platinum IV',
    },
    {
        id: '9',
        nick: 'DarkSoul',
        tag: '#BR55',
        role: 'Jungle',
        rank: 'Platinum I',
        search_role: 'Mid',
        search_rank: 'Diamond IV',
    },
    {
        id: '10',
        nick: 'IcePhoenix',
        tag: '#NA10',
        role: 'ADC',
        rank: 'Silver II',
        search_role: 'Support',
        search_rank: 'Silver I',
    },
    {
        id: '11',
        nick: 'NovaStar',
        tag: '#BR77',
        role: 'Support',
        rank: 'Bronze IV',
        search_role: 'ADC',
        search_rank: 'Silver III',
    },
    {
        id: '12',
        nick: 'FuryClaw',
        tag: '#EUW42',
        role: 'Top',
        rank: 'Diamond II',
        search_role: 'Jungle',
        search_rank: 'Master IV',
    },
    {
        id: '13',
        nick: 'RapidFang',
        tag: '#LAN01',
        role: 'Jungle',
        rank: 'Gold I',
        search_role: 'Top',
        search_rank: 'Gold II',
    },
    {
        id: '14',
        nick: 'BlazeWarden',
        tag: '#NA09',
        role: 'Mid',
        rank: 'Emerald IV',
        search_role: 'Support',
        search_rank: 'Emerald III',
    },
    {
        id: '15',
        nick: 'SkyWatcher',
        tag: '#BR88',
        role: 'ADC',
        rank: 'Platinum III',
        search_role: 'Mid',
        search_rank: 'Platinum II',
    },
    {
        id: '16',
        nick: 'FrozenDagger',
        tag: '#EUW03',
        role: 'Support',
        rank: 'Challenger I',
        search_role: 'ADC',
        search_rank: 'Grandmaster I',
    },
    {
        id: '17',
        nick: 'VoidStalker',
        tag: '#NA17',
        role: 'Top',
        rank: 'Master III',
        search_role: 'Jungle',
        search_rank: 'Master II',
    },
    {
        id: '18',
        nick: 'GoldenEye',
        tag: '#BR11',
        role: 'Mid',
        rank: 'Gold III',
        search_role: 'Support',
        search_rank: 'Gold II',
    },
    {
        id: '19',
        nick: 'TidalWave',
        tag: '#LAN66',
        role: 'Jungle',
        rank: 'Silver IV',
        search_role: 'Mid',
        search_rank: 'Silver III',
    },
    {
        id: '20',
        nick: 'NightCrawler',
        tag: '#EUW99',
        role: 'ADC',
        rank: 'Diamond I',
        search_role: 'Support',
        search_rank: 'Diamond II',
    },
    {
        id: '21',
        nick: 'IronWill',
        tag: '#BR04',
        role: 'Support',
        rank: 'Iron IV',
        search_role: 'Top',
        search_rank: 'Iron III',
    },
    {
        id: '22',
        nick: 'BloodRaven',
        tag: '#NA91',
        role: 'Top',
        rank: 'Silver I',
        search_role: 'ADC',
        search_rank: 'Gold IV',
    },
    {
        id: '23',
        nick: 'SilverKnight',
        tag: '#EUW22',
        role: 'Mid',
        rank: 'Platinum II',
        search_role: 'Jungle',
        search_rank: 'Platinum I',
    },
    {
        id: '24',
        nick: 'HexBreaker',
        tag: '#BR60',
        role: 'Jungle',
        rank: 'Emerald I',
        search_role: 'Mid',
        search_rank: 'Diamond IV',
    },
    {
        id: '25',
        nick: 'FlameArrow',
        tag: '#LAN55',
        role: 'ADC',
        rank: 'Gold IV',
        search_role: 'Support',
        search_rank: 'Gold III',
    },
    {
        id: '26',
        nick: 'StormCaller',
        tag: '#NA07',
        role: 'Support',
        rank: 'Bronze II',
        search_role: 'ADC',
        search_rank: 'Silver IV',
    },
    {
        id: '27',
        nick: 'ThunderClap',
        tag: '#EUW17',
        role: 'Top',
        rank: 'Diamond III',
        search_role: 'Top',
        search_rank: 'Diamond II',
    },
    {
        id: '28',
        nick: 'GaleForce',
        tag: '#BR23',
        role: 'Mid',
        rank: 'Master I',
        search_role: 'Jungle',
        search_rank: 'Grandmaster IV',
    },
    {
        id: '29',
        nick: 'Frostbite',
        tag: '#NA51',
        role: 'Jungle',
        rank: 'Challenger I',
        search_role: 'Mid',
        search_rank: 'Challenger I',
    },
    {
        id: '30',
        nick: 'BladeWhirl',
        tag: '#LAN20',
        role: 'ADC',
        rank: 'Emerald III',
        search_role: 'Top',
        search_rank: 'Emerald II',
    },
];
