# Generated by Django 4.1.6 on 2024-06-07 21:11

from django.db import migrations, models
import django.db.models.deletion
import games.functions
import stdimage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
                ("foundation_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                (
                    "foundation_date_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Foundation Date (written out in full)",
                    ),
                ),
                (
                    "logo",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=games.functions.get_file_company_path,
                        variations={},
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "release_date_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Release Date (written out in full)",
                    ),
                ),
                (
                    "icon",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=games.functions.get_file_game_path,
                        variations={},
                    ),
                ),
                (
                    "image",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=games.functions.get_file_game_path,
                        variations={},
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
                ("acronym", models.CharField(max_length=8, verbose_name="Acronym")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="games.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="games.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
            },
        ),
    ]
