# Generated by Django 4.1.6 on 2024-06-07 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="company",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
