# Generated by Django 4.1.6 on 2024-06-07 21:40

from django.db import migrations, models
import django.db.models.deletion
import games.functions
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_game_company_delete_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Description"),
                ),
                ("foundation_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                (
                    "foundation_date_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Foundation Date (written out in full)",
                    ),
                ),
                (
                    "logo",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=games.functions.get_file_company_path,
                        variations={},
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.company",
            ),
        ),
    ]
