# Generated by Django 4.1.6 on 2024-08-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_company_game_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraProfileGameLol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summoner_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Summoner ID"
                    ),
                ),
            ],
        ),
    ]
