# Generated by Django 4.1.6 on 2024-08-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
        ("games", "0004_extraprofilegamelol"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification",
                    models.CharField(max_length=30, verbose_name="Identification"),
                ),
                ("rank", models.CharField(max_length=15, verbose_name="Rank")),
                (
                    "extra_identification",
                    models.CharField(
                        max_length=30, verbose_name="Extra Identification"
                    ),
                ),
                (
                    "id_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="games.game",
                    ),
                ),
                (
                    "id_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExtraProfileGameLol",
        ),
    ]
