# Generated by Django 4.1.6 on 2024-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_profilegame_delete_extraprofilegamelol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilegame",
            name="extra_identification",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Extra Identification",
            ),
        ),
    ]
