export const mockMatches = [
  {
    id: 1,
    name: "ShadowGamer",
    tag: "#PRO23",
    rank: "Diamond II",
    level: 156,
    mainRole: "Support",
    secondaryRole: "Mid",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=face",
    winRate: 73,
    championsPlayed: ["Thresh", "Leona", "Nautilus"],
    playTime: "Noite",
    voiceChat: true,
    age: 24,
    lastOnline: "Online",
    compatibility: 95
  },
  {
    id: 2,
    name: "Vayne Panicat",
    tag: "#VEIGA",
    rank: "Challenger I",
    level: 600,
    mainRole: "ADC",
    secondaryRole: "Support",
    avatar: "./profile/vayne.jpg",
    winRate: 78,
    championsPlayed: ["Vayne", "Kai'sa", "Xayah"],
    playTime: "Noite",
    voiceChat: true,
    age: 25,
    lastOnline: "Online",
    compatibility: 100
  },
  {
    id: 3,
    name: "NightHunter",
    tag: "#DARK",
    rank: "Master I",
    level: 187,
    mainRole: "Jungle",
    secondaryRole: "Top",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    winRate: 71,
    championsPlayed: ["Graves", "Kha'Zix", "Evelynn"],
    playTime: "Noite",
    voiceChat: false,
    age: 26,
    lastOnline: "Online",
    compatibility: 84
  },
  {
    id: 4,
    name: "PhoenixRise",
    tag: "#FIRE",
    rank: "Diamond II",
    level: 142,
    mainRole: "Mid",
    secondaryRole: "ADC",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    winRate: 76,
    championsPlayed: ["Yasuo", "Zed", "Azir"],
    playTime: "Noite",
    voiceChat: true,
    age: 23,
    lastOnline: "Online",
    compatibility: 92
  },
  {
    id: 5,
    name: "IceStorm",
    tag: "#COLD",
    rank: "Emerald III",
    level: 129,
    mainRole: "Top",
    secondaryRole: "Jungle",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    winRate: 69,
    championsPlayed: ["Darius", "Garen", "Fiora"],
    playTime: "Madrugada",
    voiceChat: true,
    age: 25,
    lastOnline: "Online",
    compatibility: 87
  }
] as const;